version: 2

sphinx:
  configuration: docs_zh/conf.py

build:
  os: ubuntu-22.04
  apt_packages:
    - pandoc
  tools:
    python: "3.11"
  commands:
    - asdf install rust 1.91.1
    - asdf global rust 1.91.1
    - python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
    - python -m pip install --upgrade --no-cache-dir pip setuptools
    - python -m pip install --upgrade --no-cache-dir sphinx readthedocs-sphinx-ext
    - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
    - python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir ./py-hftbacktest
    - python -m sphinx -T -b html -d _build/doctrees -D language=zh_CN ./docs_zh $READTHEDOCS_OUTPUT/html
